name: My Shell Commands

on: [pull_request]

jobs:
  autofail:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"

      - name: echo the github object
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: fail if 'mylabel' label is applied
        if: contains(github.event.pull_request.labels.*.name, 'mylabel')
        run: exit 1

      - name: last step
        run: echo "should not get here if previous step failed"